#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("HIS.Resource", IsApplication=true)]

namespace HIS
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040000
			public const int Title_app = 2130968576;
			
			// aapt resource value: 0x7f040004
			public const int Title_content = 2130968580;
			
			// aapt resource value: 0x7f040001
			public const int background_login = 2130968577;
			
			// aapt resource value: 0x7f040009
			public const int button_click = 2130968585;
			
			// aapt resource value: 0x7f040005
			public const int color_button = 2130968581;
			
			// aapt resource value: 0x7f040007
			public const int controchuot = 2130968583;
			
			// aapt resource value: 0x7f040003
			public const int duongvien_login = 2130968579;
			
			// aapt resource value: 0x7f040006
			public const int duongvienedit = 2130968582;
			
			// aapt resource value: 0x7f040008
			public const int hover_button = 2130968584;
			
			// aapt resource value: 0x7f040002
			public const int login_screen = 2130968578;
			
			// aapt resource value: 0x7f04000a
			public const int title_content_ds_hiendien = 2130968586;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int background_main_noitru = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int backgroundsmartphone = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int bed2 = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int duongvienbuttonlogin = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int duongvienbuttonloginfocus = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int duongvienbuttonloginhover = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int duongvienedittextlogin = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int duongvienlayout = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int exit = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int HealthCare = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int healthcare_his = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int Icon = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int key = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int user = 2130837517;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f07000d
			public const int LinearLayout1 = 2131165197;
			
			// aapt resource value: 0x7f07000e
			public const int Noitru = 2131165198;
			
			// aapt resource value: 0x7f07000f
			public const int Phongkham = 2131165199;
			
			// aapt resource value: 0x7f07000b
			public const int btnOk = 2131165195;
			
			// aapt resource value: 0x7f070012
			public const int dm_khoaphong = 2131165202;
			
			// aapt resource value: 0x7f070013
			public const int ds_benhnhan = 2131165203;
			
			// aapt resource value: 0x7f070007
			public const int editPass = 2131165191;
			
			// aapt resource value: 0x7f070005
			public const int editUser = 2131165189;
			
			// aapt resource value: 0x7f070009
			public const int lblMSg = 2131165193;
			
			// aapt resource value: 0x7f070014
			public const int lvhistory = 2131165204;
			
			// aapt resource value: 0x7f070002
			public const int tableRow1 = 2131165186;
			
			// aapt resource value: 0x7f070004
			public const int tableRow2 = 2131165188;
			
			// aapt resource value: 0x7f070006
			public const int tableRow3 = 2131165190;
			
			// aapt resource value: 0x7f070008
			public const int tableRow4 = 2131165192;
			
			// aapt resource value: 0x7f07000a
			public const int tableRow5 = 2131165194;
			
			// aapt resource value: 0x7f070000
			public const int tb1 = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int tb2 = 2131165185;
			
			// aapt resource value: 0x7f07000c
			public const int tb3 = 2131165196;
			
			// aapt resource value: 0x7f070010
			public const int tbr_khoaphong = 2131165200;
			
			// aapt resource value: 0x7f070003
			public const int txtView = 2131165187;
			
			// aapt resource value: 0x7f070011
			public const int txtdm_khoaphong = 2131165201;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int MainPage_NoiTru = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Noitru = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Phongkham = 2130903043;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int Hello = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int ThemeHis = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
